### ISSUE TITLE
String quoting

### ISSUE THREAD

**Issue by jojoelfe** [teamtomo/starfile#35]
I have recently been struggeling with certain starfiles where strings contain spaces or quotes and have been trying to wrap my head around it. I am working on a PR to handle more edge-cases (and test these), but it is more complicated than I thought. So I thought I document my findings here first:

## What are the specs for strings in starfiles

Unfortunately, there is little. Relion says:

> String values that contain spaces can be quoted by ". An empty string becomes "".
[https://relion.readthedocs.io/en/release-3.1/Reference/Conventions.html](url)

And cisTEM chose to just simply quote all strings with a single quote '

## What does `starfile` currently do when writing

It depends on whether you write a simple block or a loop. Simple blocks don't quote at all and loops use the `csv.QUOTEMINIMAL` strategy which quotes when the string contains the sep character or a quote. However the sep character is '/t' so spaces in the string do not lead to quoting.

## What does `starfile` currently do when parsing

In loops again the `csv.QUOTEMINIMAL` strategy is used, which means double quotes are respected. There is no way currently to switch to single quotes. Parsing of files with spaces in strings that were written with `starfile` cannot be parsed because these spaces are interpreted as a delimiter.

## What can be done

- Add an option to use single quotes as quoting char for parsing and writing. That is fairly trivial.
- I initially thought one could use the `csv.QUOTENONNUMERIC` strategy, but this causes formatted floats to be quoted, which is undesirable. 
- Add this point I feel like a method has to be implemented that checks strings for spaces and then adds the quotes to the strings. Then `csv.NOQUOTE` has to be used to avoid adding quotes to the already quoted string.

**Comment by alisterburt** [comment]
Hey @jojoelfe 

Thanks for looking at this and the detailed summary! I'm away until next week but will happily review any PR when I get back :-)

**Comment by Guillawme** [comment]
In case this is helpful to you, searching for a specification turned up this paper: https://doi.org/10.1021/ci00019a005
