### ISSUE TITLE
pkg_resources DeprecationWarning

### ISSUE THREAD

**Issue by BradyAJohnston** [teamtomo/starfile#39]
I've started getting some `DeprecationWarning`s in my tests that come from `starfile`.

```python
tests/test_load.py::test_starfile_positions
  /opt/homebrew/Caskroom/miniconda/base/envs/mn/lib/python3.10/site-packages/starfile/writer.py:9: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

Should be able to just drop in replace:
```python
from pkg_resources import get_distribution
...
...
__version__ = get_distribution("starfile").version
```

with 
```python
from importlib.metadata import version
...
...
__version__ = version("starfile")
```

Thought I would flag it. Happy to open a PR with the changes if if is something you'd like.

**Comment by alisterburt** [comment]
Hey @BradyAJohnston - thanks for flagging! Happy to accept a PR, if one doesn't come in I'll do it myself over the next few days
