### ISSUE TITLE
Document new `to_string` function

### ISSUE THREAD

**Issue by jojoelfe** [teamtomo/starfile#63]
If you have time, @jahooker, that would be great!

**Comment by jahooker** [comment]
At the moment, `to_string` already has a docstring (which I unimaginatively copied from the docstring of `write`. What else would constitute documentation of `to_string`?

**Comment by jojoelfe** [comment]
That is a good question . Maybe adding a line to `docs/index.md`? Maybe it would also be a good idea to autogenerate some docs from the doc_strings, but I can also look into this.

Also, I just noticed the link to the documentation in the readme is broken. @alisterburt I'll look into how to fix this, but I might have to trouble you...

**Comment by alisterburt** [comment]
@jojoelfe oops - I'm in the process of putting together a new teamtomo.org site which links out to the various package... that isn't quite done but I've already moved the existing site to https://github.com/teamtomo/teamtomo-site-archive

I wasn't expecting child sites `teamtomo.org/starfile` etc to be affected but I guess they need a parent - this will be fixed once I've pushed the new site to github, sorry about that! 🙂

**Comment by jojoelfe** [comment]
@alisterburt no worries, just wanted to point it out.

@jahooker unless there is something you want to add, this might just be done by #64 

https://teamtomo.github.io/starfile/
