### ISSUE TITLE
starfile.write ignores overwrite=True argument in the newest versions

### ISSUE THREAD

**Issue by rsanchezgarc** [teamtomo/starfile#72]
* starfile version: 0.5.8 and master branch
* Python version: 3.11
* Operating System: Ubuntu 22.04

### Description

The line `star file.write(data, name, overwrite=True)`  generates a backup file of the original file named fname+"~". In past versions, it just overwrote the file if overwrite was True; otherwise, it raised an exception. 

This happens here https://github.com/teamtomo/starfile/blob/a2e9927c17082917dd507f7d5024f7488248e8d5/src/starfile/writer.py#L44

It would be great if the overwrite=True behaviour were returned to the API so that unwanted files are not generated.

**Comment by alisterburt** [comment]
ahh, good catch - thanks for the report!

**Comment by jojoelfe** [comment]
I kind of like the backup mechanism. But not super attached to it. I think my ideal behavior would be:

- Default: Overwrite, but create backup and print warning
- overwrite=True: Overwrite no warning or backup
- overwrite=False: Fail with error message if file already exists

**Comment by rsanchezgarc** [comment]
both options seem sensible to me. I just want it to keep the old behaviour if overwrite=True

**Comment by alisterburt** [comment]
closed by #76
